interface:
  initial:
    user: "nobody"
    host: "local"
    wdir: "~"
  style:
    etc: ""
    hostname: fg:ansicyan
    path: fg:ansiblue bold

connection:
  address: 127.0.0.1
  port: 1729
  deny_custom_server: true

data:
  directory: data/
  meta: meta.yml
  obj: objects.json
  stars: STARS

game:
  turnlength: 300

telemetry:
  decimal: 3
  indent: 3
